import Image from "next/image";
import Link from "next/link";
import PretoriaPhoto from "@/components/PretoriaPhoto";
import ProjectCard from "@/components/ProjectCard";

export default function Home() {
  return (
    <>
      <section className="grid md:grid-cols-[58%_42%] border-b border-line">
        <div className="px-6 md:px-14 py-20 md:py-28 flex items-center"><div className="max-w-3xl"><p className="chapter-label mb-7">A studio for expensive assumptions</p><h1 className="font-display text-[56px] sm:text-[72px] lg:text-[96px] leading-[0.92] tracking-[-0.03em]">Noticed,<br /><em className="text-green">not invented.</em></h1><p className="text-lg text-muted max-w-xl mt-8 leading-relaxed">We notice the problems people have learned to live with, understand why they persist, and build systems that make them easier to solve.</p><div className="flex flex-wrap gap-8 items-center mt-10"><Link href="#work" className="text-sm bg-green text-white px-6 py-3.5 hover:bg-green/90 transition-colors">Explore the work →</Link><Link href="/contact" className="font-display italic text-xl text-text/70 hover:text-green">Start a project ↗</Link></div></div></div>
        <PretoriaPhoto />
      </section>

      <section className="px-6 py-20 md:py-28"><div className="max-w-4xl mx-auto grid md:grid-cols-[180px_1fr] gap-8"><div><p className="chapter-label">01 / Our Principle</p><div className="rule-gold mt-4" /></div><div><h2 className="font-display text-4xl md:text-6xl leading-[1.04]">Don&apos;t assume.<br /><em>Observe, test, verify.</em></h2><p className="text-muted text-lg mt-7 max-w-xl">The fix isn&apos;t always AI, and it isn&apos;t always the same fix twice.</p></div></div></section>

      <section id="engine" className="px-6 py-20 md:py-28 bg-bg-alt border-y border-line"><div className="max-w-5xl mx-auto"><p className="chapter-label mb-6">02 / The AiForm Engine</p><h2 className="font-display text-4xl md:text-6xl max-w-3xl leading-tight">What are people currently being asked to assume?</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-9 mt-14">{[["01", "Parse", "Give messy, real-world input a useful shape."], ["02", "Verify", "Check a claim against evidence, not convenience."], ["03", "Understand", "Turn evidence into something a person can act on."], ["04", "Match", "Connect the right buyer, supplier, answer, or fit."]].map(([number, title, copy]) => <div key={number} className="border-t border-line pt-5"><p className="chapter-label mb-3">{number}</p><h3 className="font-display text-3xl text-green">{title}</h3><p className="text-sm text-muted leading-relaxed mt-3">{copy}</p></div>)}</div></div></section>

      <section id="work" className="px-6 py-20 md:py-28"><div className="max-w-5xl mx-auto"><p className="chapter-label mb-6">03 / Built by AiForm</p><h2 className="font-display text-4xl md:text-6xl mb-14">Products, studio projects,<br /><em>and experiments.</em></h2><PortfolioGroup title="Products" tagline="Problems we choose to pursue"><ProjectCard name="AiForm Procure" tag="Product" desc="A procurement system built around fragmented information, compliance, and trust." status="Live · Pilot phase" href="https://www.aiformprocure.co.za" accent="var(--color-green)" /></PortfolioGroup><PortfolioGroup title="Studio Projects" tagline="Problems brought to us"><ProjectCard name="Residential Construction Portfolio Site" tag="Website" desc="A clear, credible portfolio site for a residential construction business." status="Delivered" accent="var(--color-clay)" /><ProjectCard name="Kutlwano Tutoring" tag="Website" desc="A focused site bringing two tutoring audiences and pricing models into one clear experience." status="Live" href="https://kutlwanotutoring.co.za" accent="var(--color-sage)" /><ProjectCard name="Mathabo Crochet" tag="Brand pack" desc="A visual brand foundation for a handmade crochet business." status="Delivered · No site" accent="var(--color-gold)" /></PortfolioGroup><PortfolioGroup title="Experiments" tagline="Things we're still figuring out"><ProjectCard name="AutoDesign Studio" tag="Experiment" desc="Exploring how AI can support faster, more deliberate design work." status="Exploring" accent="var(--color-purple)" /><ProjectCard name="Vibe Coders Hub" tag="Experiment" desc="Exploring a more accessible way into building with code." status="Exploring" accent="var(--color-purple)" /><ProjectCard name="AI Builder Collective" tag="Experiment" desc="Exploring what a community around practical AI building could become." status="Exploring" accent="var(--color-purple)" /><ProjectCard name="AiForm Construct" tag="Experiment" desc="Exploring tools for clearer construction information and decisions." status="Exploring" accent="var(--color-purple)" /></PortfolioGroup></div></section>

      <section id="founder" className="px-6 py-20 md:py-28 bg-bg-alt border-y border-line"><div className="max-w-5xl mx-auto grid md:grid-cols-[0.8fr_1.2fr] gap-12 md:gap-20 items-center"><div className="relative aspect-[4/5] max-w-sm"><Image src="/images/founder.jpg" alt="Thabiso Eric Motaung, founder of AiForm Studio" fill sizes="(max-width: 768px) 100vw, 400px" className="object-cover grayscale" /></div><div><p className="chapter-label mb-6">04 / The Studio</p><h2 className="font-display text-4xl md:text-6xl leading-tight">Founder-led.<br /><em>Research-driven.</em></h2><p className="font-display italic text-xl text-green mt-7">Identify → inspect → test → build → observe → revise.</p><p className="text-muted leading-relaxed mt-7">AiForm Studio is founder-led by Thabiso Eric Motaung, who designs and builds each engagement from research through delivery. Alongside the studio, he is a Senior Lecturer at the University of Pretoria — experience that keeps the work close to how people learn, reason, and get stuck.</p><div className="grid sm:grid-cols-3 gap-6 mt-9 pt-6 border-t border-line text-xs text-muted"><div><span className="block text-green mb-2">ROLE</span>Founder &amp; Builder</div><div><span className="block text-green mb-2">ALSO</span>Senior Lecturer</div><div><span className="block text-green mb-2">BASED</span>Pretoria, South Africa</div></div></div></div></section>

      <section className="px-6 py-20 md:py-28"><div className="max-w-4xl mx-auto"><p className="chapter-label mb-6">05 / What We&apos;ve Learned</p><h2 className="font-display text-4xl md:text-6xl">“Claims should survive<br /><em>contact with reality.”</em></h2><div className="mt-12 border-t border-line">{["A configuration that ‘should’ be correct isn’t correct until it’s tested.", "A security policy that looks scoped isn’t safe until it’s verified.", "A feature isn’t fixed because the code changed. It’s fixed when the behaviour changes.", "A product doesn’t support something because the website says it does."].map((line, i) => <div key={line} className="grid grid-cols-[40px_1fr] gap-4 py-5 border-b border-line"><span className="font-display text-gold">0{i + 1}</span><p>{line}</p></div>)}</div><p className="font-display italic text-2xl text-clay mt-9">Less assumption. More evidence.</p></div></section>

      <section className="px-6 py-24 md:py-36 bg-bg-alt border-y border-line text-center"><p className="chapter-label mb-7">06 / How We Work</p><h2 className="font-display text-6xl md:text-8xl lg:text-[112px] leading-[0.9] tracking-[-0.03em]">We don&apos;t start<br />with <em className="text-green">AI.</em></h2><p className="font-display italic text-2xl mt-8">We start with the problem.</p><p className="text-muted max-w-xl mx-auto mt-6 leading-relaxed">Sometimes the answer needs AI. Sometimes it needs better data, automation, or simply software designed properly.</p><p className="font-display italic text-xl text-green mt-8">Technology serves the problem, not the other way around.</p></section>

      <section className="px-6 py-24 md:py-32 text-center"><p className="chapter-label mb-7">07 / Where We Look Next</p><h2 className="font-display text-4xl md:text-6xl max-w-3xl mx-auto">No fixed industry.<br /><em>A very specific kind of problem.</em></h2><p className="text-muted mt-8 max-w-xl mx-auto leading-relaxed">Documents everywhere. Important claims that are difficult to verify. Two parties deciding whether they can trust one another. Hours of work that software should do in seconds.</p><p className="font-display text-2xl text-green mt-8">What haven&apos;t we noticed yet?</p></section>

      <section className="px-6 py-24 md:py-32 bg-bg-alt border-t border-line text-center"><p className="font-display italic text-2xl text-muted mb-5">Built in Pretoria. Looking everywhere.</p><h2 className="font-display text-4xl md:text-6xl max-w-3xl mx-auto">If something important is being trusted on assumption, <em>we&apos;re interested.</em></h2><Link href="/contact" className="inline-block mt-10 text-sm bg-green text-white px-6 py-3.5 hover:bg-green/90 transition-colors">Start a project ↗</Link></section>
    </>
  );
}

function PortfolioGroup({ title, tagline, children }: { title: string; tagline: string; children: React.ReactNode }) {
  return <div className="mb-14"><div className="flex flex-wrap items-baseline gap-x-4 gap-y-1 mb-5"><h3 className="font-display text-3xl">{title}</h3><p className="font-display italic text-lg text-muted">{tagline}</p></div><div className="grid md:grid-cols-2 gap-5">{children}</div></div>;
}
