import Image from "next/image";
import Link from "next/link";
import PretoriaPhoto from "@/components/PretoriaPhoto";

const engine = [["01","Parse","Give messy, real-world information a useful shape."],["02","Verify","Check claims against evidence, not convenience."],["03","Understand","Turn evidence into something people can act on."],["04","Match","Connect the right buyer, supplier, answer, or fit."]];
const work = [["Residential construction","Studio project / Gauteng","A clear portfolio for a building business, designed around proof of work and direct enquiries."],["Kutlwano Tutoring","Studio project / Education / Live","One focused experience for two audiences, with distinct learning needs and pricing models."],["Mathabo Crochet","Studio project / Brand","A visual foundation for a handmade business: identity, palette, typography, and social templates."],["AiForm Construct","Experiment / Construction","An early investigation into permits, contractor verification, and clearer project documentation."]];

export default function Home() {
  return <>
    <section className="editorial-grid min-h-[78vh] items-center py-20 md:py-28">
      <div className="col-span-12"><p className="chapter-label mb-10">A studio for expensive assumptions</p><h1 className="font-display hero-title">Noticed,<br/><span className="text-green">not invented.</span></h1></div>
      <div className="col-span-12 md:col-start-8 md:col-span-5 mt-16 md:mt-24"><p className="text-lg md:text-xl leading-relaxed">We notice the problems people have learned to live with, understand why they persist, and build systems that make them easier to solve.</p><div className="flex flex-wrap gap-8 items-center mt-9"><Link href="#work" className="link-arrow">Explore the work →</Link><Link href="/contact" className="text-lg font-semibold text-green">Start a project ↗</Link></div></div>
    </section>
    <PretoriaPhoto/>
    <section id="studio" className="editorial-grid bg-green text-white py-24 md:py-40"><p className="col-span-12 md:col-span-2 chapter-label chapter-label-light">01 / The studio</p><div className="col-span-12 md:col-start-3 md:col-span-9 mt-12 md:mt-0"><h2 className="statement">We don&apos;t start<br/>with technology.</h2><p className="font-display text-3xl md:text-5xl text-[#e0c98f] mt-8">We start with what isn&apos;t working.</p></div><p className="col-span-12 md:col-start-9 md:col-span-4 mt-20 text-sm leading-relaxed text-white/75">The fix isn&apos;t always AI, and it isn&apos;t always the same fix twice. We inspect the evidence, test the assumption, build what is useful, and revise when reality disagrees.</p></section>
    <section id="engine" className="editorial-grid py-24 md:py-40"><p className="col-span-12 md:col-span-2 chapter-label">02 / The engine</p><h2 className="col-span-12 md:col-start-3 md:col-span-9 statement mt-10 md:mt-0">What are people currently<br/><span className="text-green">being asked to assume?</span></h2><p className="col-span-12 md:col-start-8 md:col-span-5 mt-12 text-muted leading-relaxed">A recurring AiForm approach when information, verification, and trust sit at the centre of a problem—not a claim that every project follows the same four stages.</p><div className="col-span-12 mt-20 border-t border-line grid md:grid-cols-4">{engine.map(([n,t,c],i)=><div key={n} className={`engine-step py-8 md:py-10 ${i ? "md:border-l md:border-line md:pl-7":""}`}><p className="chapter-label">{n}</p><h3 className="font-display text-4xl lg:text-5xl mt-7">{t}</h3><p className="text-sm text-muted leading-relaxed mt-5 max-w-[15rem]">{c}</p></div>)}</div><p className="col-span-12 font-display text-green text-2xl md:text-3xl border-t border-line pt-7">Parse → Verify → Understand → Match</p></section>
    <section id="work" className="py-24 md:py-40 border-t border-line"><div className="editorial-grid"><p className="col-span-12 md:col-span-2 chapter-label">03 / Work</p><div className="col-span-12 md:col-start-3 md:col-span-9 mt-10 md:mt-0"><h2 className="statement">Built by AiForm.</h2><p className="font-display text-3xl md:text-5xl text-green mt-5">Different problems. Same instinct.</p></div></div>
      <article className="mt-20 md:mt-32 bg-[#e9e1ca] py-14 md:py-24"><div className="editorial-grid items-end"><div className="col-span-12 md:col-span-4 mb-12 md:mb-0 md:pr-8"><p className="chapter-label">Product / Procurement / Live</p><h3 className="font-display text-5xl md:text-7xl mt-6">AiForm<br/><span className="text-green">Procure.</span></h3><p className="text-muted leading-relaxed mt-8">A procurement system built around fragmented information, compliance, and trust—connecting verified South African suppliers with serious buyers.</p><a href="https://www.aiformprocure.co.za" target="_blank" rel="noreferrer" className="link-arrow mt-9">View product ↗</a></div><div className="col-span-12 md:col-start-5 md:col-span-8 product-frame"><div className="product-bar">AIFORM PROCURE / SUPPLIER OVERVIEW</div><div className="product-ui"><aside><b>Procure</b><span>Overview</span><span>Suppliers</span><span>Verification</span><span>Opportunities</span></aside><main><p>SUPPLIER OVERVIEW</p><h4>Trust, made visible.</h4><div><span><b>148</b>Verified suppliers</span><span><b>32</b>Open opportunities</span><span><b>96%</b>Complete profiles</span></div></main></div></div></div></article>
      <div className="editorial-grid mt-24 md:mt-36"><div className="col-span-12 md:col-span-4 work-type"><p className="chapter-label">Products</p><h3>Problems we choose to pursue.</h3></div><div className="col-span-12 md:col-span-4 work-type"><p className="chapter-label">Studio projects</p><h3>Problems brought to us.</h3></div><div className="col-span-12 md:col-span-4 work-type"><p className="chapter-label text-purple">Experiments</p><h3>Things we&apos;re still figuring out.</h3></div><div className="col-span-12 mt-20 border-t border-line">{work.map(([n,m,c])=><article key={n} className="selected-row"><p>{m}</p><h3>{n}</h3><p>{c}</p></article>)}</div></div>
    </section>
    <section className="editorial-grid bg-clay text-white py-24 md:py-40"><p className="col-span-12 md:col-span-2 chapter-label chapter-label-light">04 / Principle</p><h2 className="col-span-12 md:col-start-3 md:col-span-9 statement mt-10 md:mt-0">Claims should survive<br/><span>contact with reality.</span></h2><p className="col-span-12 md:col-start-8 md:col-span-5 mt-16 leading-relaxed text-white/80">A configuration isn&apos;t correct until it&apos;s tested. A feature isn&apos;t fixed because the code changed. It&apos;s fixed when the behaviour changes.</p></section>
    <section id="founder" className="editorial-grid py-24 md:py-40"><p className="col-span-12 md:col-span-2 chapter-label">05 / Founder</p><div className="col-span-12 md:col-start-3 md:col-span-4 mt-10 md:mt-0 relative aspect-[4/5]"><Image src="/images/founder.jpg" alt="Thabiso Eric Motaung, founder of AiForm Studio" fill sizes="(max-width:768px) 100vw, 34vw" className="object-cover grayscale"/></div><div className="col-span-12 md:col-start-8 md:col-span-5 mt-12 md:mt-0"><h2 className="font-display text-5xl md:text-7xl leading-[.94]">Founder-led.<br/><span className="text-green">Research-driven.</span></h2><p className="text-muted leading-relaxed mt-9">AiForm Studio is led by Thabiso Eric Motaung, who designs and builds each engagement from research through delivery. Alongside the studio, he is a Senior Lecturer at the University of Pretoria—experience that keeps the work close to how people learn, reason, and get stuck.</p><p className="font-display text-2xl text-green mt-10">Identify → inspect → test → build → observe → revise.</p></div></section>
    <section className="editorial-grid border-t border-line py-24 md:py-40">
      <p className="col-span-12 md:col-span-2 chapter-label">06 / The mark</p>
      <div className="col-span-12 md:col-start-3 md:col-span-5 mt-10 md:mt-0">
        <h2 className="font-display text-5xl leading-[.95] md:text-7xl">The mark was<br/><span className="text-green">noticed, too.</span></h2>
        <p className="mt-9 max-w-xl text-lg leading-relaxed text-muted">AiForm&apos;s A began with a small moth resting on a wall in Pretoria. Its wings naturally formed the shape we were looking for. We didn&apos;t design the coincidence. We noticed it.</p>
      </div>
      <div className="col-span-8 col-start-3 mt-16 flex items-center justify-center border-y border-line py-14 sm:col-span-5 sm:col-start-5 md:col-span-3 md:col-start-9 md:mt-0 md:py-16">
        <Image src="/images/aiform-mark.png" alt="The gold AiForm A-moth mark" width={472} height={588} sizes="(max-width: 768px) 50vw, 22vw" className="brand-mark h-auto w-28 sm:w-36 md:w-44" />
      </div>
      <div className="col-span-12 mt-14 grid grid-cols-[1fr_auto_1fr_auto_1fr] items-center gap-3 border-t border-line pt-6 text-center text-[10px] font-semibold uppercase tracking-[.12em] text-muted md:col-start-3 md:col-span-9 md:text-xs">
        <span>Moth</span><span aria-hidden="true" className="text-gold">→</span><span>Letter A</span><span aria-hidden="true" className="text-gold">→</span><span>AiForm mark</span>
      </div>
    </section>
    <section className="editorial-grid bg-bg-alt py-28 md:py-52"><p className="col-span-12 md:col-span-2 chapter-label">07 / How we work</p><h2 className="col-span-12 md:col-start-2 md:col-span-8 statement mt-12">We don&apos;t start<br/><span className="text-green">with AI.</span></h2><div className="col-span-12 md:col-start-9 md:col-span-4 mt-16"><p className="text-muted leading-relaxed">Sometimes the answer needs AI. Sometimes it needs better data. Sometimes it needs automation. Sometimes it just needs software designed properly.</p><p className="font-display text-2xl text-green mt-7">Technology serves the problem, not the other way around.</p></div></section>
    <section className="editorial-grid py-28 md:py-52"><p className="col-span-12 md:col-span-2 chapter-label">08 / Where next</p><h2 className="col-span-12 md:col-start-3 md:col-span-9 statement mt-12 md:mt-0">What haven&apos;t we<br/><span className="text-green">noticed yet?</span></h2><p className="col-span-12 md:col-start-8 md:col-span-5 text-muted leading-relaxed mt-16">Documents everywhere. Important claims that are difficult to verify. Two parties deciding whether they can trust one another. Hours of work that software should do in seconds.</p></section>
  </>;
}
