"use client";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { budgetOptions } from "@/lib/inquiry";
type SimpleDraft = { name: string; organisation: string; email: string; phone: string; problem: string; budget: string; honeypot: string; startedAt: number };
const EMPTY: SimpleDraft = { name: "", organisation: "", email: "", phone: "", problem: "", budget: "", honeypot: "", startedAt: 0 };
const STORAGE_KEY = "aiform-simple-inquiry-v1";
export default function IntakeForm() {
  const [draft, setDraft] = useState<SimpleDraft>(EMPTY); const [errors, setErrors] = useState<Record<string, string>>({}); const [submitting, setSubmitting] = useState(false); const [submitted, setSubmitted] = useState(false); const [submitError, setSubmitError] = useState("");
  useEffect(() => { const restore = window.setTimeout(() => { try { const saved = sessionStorage.getItem(STORAGE_KEY); const restored = saved ? JSON.parse(saved) as Partial<SimpleDraft> : {}; setDraft({ ...EMPTY, ...restored, startedAt: Date.now() }); } catch { setDraft({ ...EMPTY, startedAt: Date.now() }); } }, 0); return () => window.clearTimeout(restore); }, []);
  useEffect(() => { if (!draft.startedAt || submitted) return; try { sessionStorage.setItem(STORAGE_KEY, JSON.stringify(draft)); } catch {} }, [draft, submitted]);
  const update = (field: keyof SimpleDraft, value: string) => { setDraft((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: "" })); };
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const nextErrors: Record<string, string> = {}; if (!draft.name.trim()) nextErrors.name = "Please let us know your name."; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email.trim())) nextErrors.email = "Please enter a valid email address."; if (!draft.problem.trim()) nextErrors.problem = "Tell us a little about what you are trying to solve."; if (Object.keys(nextErrors).length) { setErrors(nextErrors); return; } setSubmitting(true); setSubmitError(""); try { const response = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enquiryType: "unsure", currentProblems: ["other"], otherProblemNote: draft.problem, audiences: ["not_sure"], desiredOutcomes: ["still_figuring_out"], projectStage: "not_sure", timeline: "flexible", additionalContext: draft.problem, budget: draft.budget || undefined, name: draft.name, organisation: draft.organisation, email: draft.email, phone: draft.phone, honeypot: draft.honeypot, startedAt: draft.startedAt }) }); const result = await response.json() as { ok?: boolean; error?: string }; if (!response.ok || !result.ok) throw new Error(result.error || "We couldn't send that yet. Please try again."); setSubmitted(true); try { sessionStorage.removeItem(STORAGE_KEY); } catch {} } catch (error) { setSubmitError(error instanceof Error ? error.message : "We couldn't send that yet. Please try again."); } finally { setSubmitting(false); } }
  if (submitted) return <div className="border-t-2 border-gold pt-8" role="status"><p className="chapter-label">Enquiry received</p><h2 className="mt-5 font-display text-4xl text-green">Thank you. We&apos;ll be in touch.</h2><p className="mt-5 max-w-xl leading-relaxed text-muted">Your note is safely with AiForm. Expect a reply at the email address you provided.</p></div>;
  return <form onSubmit={submit} noValidate aria-labelledby="inquiry-form-title" className="border-t-2 border-gold pt-8"><div><p className="chapter-label">A short note is enough</p><h2 id="inquiry-form-title" className="mt-4 font-display text-3xl">Tell us about the problem.</h2></div><div className="mt-8 grid gap-6 sm:grid-cols-2"><Field label="Name" required error={errors.name}><input className="field-input" value={draft.name} onChange={(e) => update("name", e.target.value)} autoComplete="name" aria-invalid={Boolean(errors.name)} /></Field><Field label="Business / organisation"><input className="field-input" value={draft.organisation} onChange={(e) => update("organisation", e.target.value)} autoComplete="organization" /></Field><Field label="Email" required error={errors.email}><input className="field-input" type="email" value={draft.email} onChange={(e) => update("email", e.target.value)} autoComplete="email" aria-invalid={Boolean(errors.email)} /></Field><Field label="WhatsApp / phone" optional><input className="field-input" type="tel" value={draft.phone} onChange={(e) => update("phone", e.target.value)} autoComplete="tel" /></Field><div className="sm:col-span-2"><Field label="What are you trying to solve?" required error={errors.problem}><textarea className="field-textarea" value={draft.problem} onChange={(e) => update("problem", e.target.value)} placeholder="Describe what is difficult, slow, unclear or not working." aria-invalid={Boolean(errors.problem)} /></Field></div><div className="sm:col-span-2"><Field label="Budget range" optional><select className="field-input" value={draft.budget} onChange={(e) => update("budget", e.target.value)}><option value="">Prefer not to say yet</option>{budgetOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Field></div></div><div className="intake-honeypot" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={draft.honeypot} onChange={(e) => update("honeypot", e.target.value)} /></label></div>{submitError ? <p className="mt-6 text-sm text-clay" role="alert">{submitError} You can also email <a className="underline" href="mailto:hello@aiformstudio.co.za">hello@aiformstudio.co.za</a>.</p> : null}<button type="submit" disabled={submitting} className="mt-8 min-h-12 bg-green px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-clay focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-gold disabled:opacity-60">{submitting ? "Sending…" : "Tell us about the problem"}</button></form>;
}
function Field({ label, optional = false, required = false, error, children }: { label: string; optional?: boolean; required?: boolean; error?: string; children: ReactNode }) { return <label className="block"><span className="field-label">{label} {optional ? <span className="font-normal text-muted">(optional)</span> : null}{required ? <span className="text-clay" aria-hidden="true"> *</span> : null}</span>{children}{error ? <span className="field-error" role="alert">{error}</span> : null}</label>; }
